### ISSUE TITLE
Next.js 8 (with bulma v2 and v3) build error

### ISSUE THREAD

**Issue by Rapol** [couds/react-bulma-components#185]
I have tried both v2 and v3 and I'm running into the same issue during build:
```
TypeError: Cannot read property 'propTypes' of undefined
    at Module../node_modules/react-bulma-components/lib/modifiers/index.js
```

Node: v10.15.3
Next: 8.0.3
React: 16.8
react-bulma-components: v2 & v3

Try it here:
https://github.com/Rapol/next-bulma-components-error

**Comment by MrCreeper1008** [comment]
Have you followed the installation instruction for next.js? It's shown in README.

**Comment by couds** [comment]
Hi. You need to install the peer dependencies (your package.json is missing the prop-types module)

**Comment by Rapol** [comment]
Hi, thanks for the fast response! 

I didnt add it to the package.json since during installation npm didnt throw any warnings about prop-types missing(seems that an eslint plugin already has it). But it does throw warnings about react 16.3 not found. I explicitly added prop-types but Im still getting the same error. See below:

```
TypeError: Cannot read property 'propTypes' of undefined
Module../node_modules/react-bulma-components/lib/modifiers/index.js
./src/modifiers/index.js:10
   7 | const compose = (...fns) => args => fns.reduce((arg, fn) => fn(arg), args);
   8 | 
   9 | export default {
> 10 |   propTypes: {
  11 |     ...helpers.propTypes,
  12 |     ...responsive.propTypes,
  13 |     ...colors.propTypes,
```

@MrCreeper1008 I am using the next.config.js that the readme has. It is a little difference because next-plugin-transpile-modules has been renamed and I customized the default path to the _variables.scss

```
const withSass = require('@zeit/next-sass');
const withTM = require('next-transpile-modules');

module.exports = withTM(withSass({
  transpileModules: ['react-bulma-components'],
  sassLoaderOptions: {
    includePaths: ['./styles'],
  },
}));
```

**Comment by MrCreeper1008** [comment]
Is a full stack trace of the error available? That would be helpful. Thanks!

**Comment by Rapol** [comment]
Here:

```
TypeError: Cannot read property 'propTypes' of undefined
    at Module../node_modules/react-bulma-components/lib/modifiers/index.js (/Users/rapol/Projects/next-bulma/.next/server/static/development/pages/index.js:3724:49)
    at __webpack_require__ (/Users/rapol/Projects/next-bulma/.next/server/static/development/pages/index.js:23:31)
    at Module../node_modules/react-bulma-components/lib/components/image/image.js (/Users/rapol/Projects/next-bulma/.next/server/static/development/pages/index.js:2486:41)
    at __webpack_require__ (/Users/rapol/Projects/next-bulma/.next/server/static/development/pages/index.js:23:31)
    at Object../node_modules/react-bulma-components/lib/components/image/index.js (/Users/rapol/Projects/next-bulma/.next/server/static/development/pages/index.js:2816:38)
    at __webpack_require__ (/Users/rapol/Projects/next-bulma/.next/server/static/development/pages/index.js:23:31)
    at Module../node_modules/react-bulma-components/lib/components/card/components/image.js (/Users/rapol/Projects/next-bulma/.next/server/static/development/pages/index.js:1639:37)
    at __webpack_require__ (/Users/rapol/Projects/next-bulma/.next/server/static/development/pages/index.js:23:31)
    at Module../node_modules/react-bulma-components/lib/components/card/card.js (/Users/rapol/Projects/next-bulma/.next/server/static/development/pages/index.js:427:37)
    at __webpack_require__ (/Users/rapol/Projects/next-bulma/.next/server/static/development/pages/index.js:23:31)
    at Object../node_modules/react-bulma-components/lib/components/card/index.js (/Users/rapol/Projects/next-bulma/.next/server/static/development/pages/index.js:1764:37)
    at __webpack_require__ (/Users/rapol/Projects/next-bulma/.next/server/static/development/pages/index.js:23:31)
    at Module../components/Content.js (/Users/rapol/Projects/next-bulma/.next/server/static/development/pages/index.js:107:100)
    at __webpack_require__ (/Users/rapol/Projects/next-bulma/.next/server/static/development/pages/index.js:23:31)
    at Module../pages/index.js (/Users/rapol/Projects/next-bulma/.next/server/static/development/pages/index.js:4047:77)
    at __webpack_require__ (/Users/rapol/Projects/next-bulma/.next/server/static/development/pages/index.js:23:31)
```

The transpiled code fails because `_helpers.default` is null when spreading it in `modifiers/index.js`:
```
var _default = {
  propTypes: _objectSpread({}, _helpers.default.propTypes, _responsives.default.propTypes, _colors.default.propTypes, _typography.default.propTypes),
...
};
```

If possible, try to recreate the issue with this repo (https://github.com/Rapol/next-bulma-components-error). Don't wanna waste anyone time if it's a bad local config. I'm now leaning that the issue might be a bad configuration of next-transpile-modules.

**Comment by MrCreeper1008** [comment]
Yes I'll try to. Will get back to you asap.

**Comment by MrCreeper1008** [comment]
I have no idea why, but `require('./helpers')` returns an empty object in the transpiled code:
```
var _helpers = _interopRequireDefault(require("./helpers"));
```
thus causing
```
_helpers.default
```
to be undefined.

**Comment by rynomad** [comment]
Just ran into this; the problem is that you're referencing the already transpiled files in the `lib` directory or react-bulma-components. [This change](https://github.com/rynomad/next-bulma-components-error/commit/6ecac654df47c3983b2ebba159f841c7b1203dcc) will get you going.

**Comment by Rapol** [comment]
Nice catch 👏 👏 . Will close the issue since the PR changes document how to avoid this.
