### ISSUE TITLE
[HELP] Next.js throws error when importing Bulma component

### ISSUE THREAD

**Issue by FunctionDJ** [couds/react-bulma-components#324]
Steps to reproduce:
• `npm init next-app example`
• `npm i -D react-bulma-components`
• `npm run dev`
• import a Bulma component into index.js

Is this a Next.js issue, maybe because of Webpack 5? The error messages basically don't contain any meaningful information:
```
Error: Failed to load /
    at loadComponents (C:\Users\Function\Documents\Git\static\mbsr\next-rebuild\node_modules\next\dist\next-server\server\load-components.js:1:1554)
    at async DevServer.findPageComponents (C:\Users\Function\Documents\Git\static\mbsr\next-rebuild\node_modules\next\dist\next-server\server\next-server.js:76:257)
    at async DevServer.renderToHTML (C:\Users\Function\Documents\Git\static\mbsr\next-rebuild\node_modules\next\dist\next-server\server\next-server.js:137:542)
    at async DevServer.renderToHTML (C:\Users\Function\Documents\Git\static\mbsr\next-rebuild\node_modules\next\dist\server\next-dev-server.js:36:578)
    at async DevServer.render (C:\Users\Function\Documents\Git\static\mbsr\next-rebuild\node_modules\next\dist\next-server\server\next-server.js:74:255)
    at async Object.fn (C:\Users\Function\Documents\Git\static\mbsr\next-rebuild\node_modules\next\dist\next-server\server\next-server.js:58:672)
    at async Router.execute (C:\Users\Function\Documents\Git\static\mbsr\next-rebuild\node_modules\next\dist\next-server\server\router.js:25:67)
    at async DevServer.run (C:\Users\Function\Documents\Git\static\mbsr\next-rebuild\node_modules\next\dist\next-server\server\next-server.js:68:1042)
    at async DevServer.handleRequest (C:\Users\Function\Documents\Git\static\mbsr\next-rebuild\node_modules\next\dist\next-server\server\next-server.js:32:504)```

**Comment by couds** [comment]
Seems that with webpack 5 the imports were mess up. I will take a look later.

**Comment by FunctionDJ** [comment]
Thank you! I guess this is a [Bug] then and not a [Help] question

**Comment by couds** [comment]
@FunctionDJ I just release v4.0.3. can you try it and let me know if the issue persist?

**Comment by Mause** [comment]
v4.0.3 has fixed the same issue for me 👍

**Comment by couds** [comment]
I'm closing this. Reopen if this happen again! Thanks =)

**Comment by FunctionDJ** [comment]
Yep, it's working 👍
