### ISSUE TITLE
Storybook fails to load select Component

### ISSUE THREAD

**Issue by zargold** [couds/react-bulma-components#326]
**Describe the bug**
The Storybook for select component does not load/gives an error.

**To Reproduce**
1. Go to https://react-bulma.dev/en/storybook.
2. Click on Select (within Form section)
3. Click on Canvas (since Docs tab doesn't work)

**Expected behavior**
The Bulma-React select Component

**Screenshots**
This is live on your demo site:
TypeError: Cannot read property 'type' of null
    at isIcon (https://couds.github.io/react-bulma-components/main.21d42c25.iframe.bundle.js:1:240482)
    at https://couds.github.io/react-bulma-components/main.21d42c25.iframe.bundle.js:1:240657
    at https://couds.github.io/react-bulma-components/vendors~main.338d86d4.iframe.bundle.js:2:1479881
    at O (https://couds.github.io/react-bulma-components/vendors~main.338d86d4.iframe.bundle.js:2:1479012)
    at O (https://couds.github.io/react-bulma-components/vendors~main.338d86d4.iframe.bundle.js:2:1479427)
    at Object.P [as map] (https://couds.github.io/react-bulma-components/vendors~main.338d86d4.iframe.bundle.js:2:1479847)
    at Control (https://couds.github.io/react-bulma-components/main.21d42c25.iframe.bundle.js:1:240620)
    at Ch (https://couds.github.io/react-bulma-components/vendors~main.338d86d4.iframe.bundle.js:2:1541679)
    at ck (https://couds.github.io/react-bulma-components/vendors~main.338d86d4.iframe.bundle.js:2:1593879)
    at bk (https://couds.github.io/react-bulma-components/vendors~main.338d86d4.iframe.bundle.js:2:1580961)

**Versions**
- `react-bulma-components:`:
- `bulma`:
- `react`:
- Browser:Chrome version 90.0.4430.212 (Official Build) (x86_64)

**Additional context**

**Comment by luhis** [comment]
i can't storybook to run on my machine, but it appears to be fixed in this commit:
https://github.com/couds/react-bulma-components/commit/45f75b201e11de7157875f40c756ded5b5bbc75e#diff-22e9a8b4d3f57dd28d5a14edfcf54385b2a4d7900bfc7e2c153ced5bab4357e3

This icon is null, and the version of code deployed is missing that null check.

I think the storybook just needs to be redeployed.

**Comment by couds** [comment]
Hi @zargold as @luhis said the fix was already there but I forgot to redeploy storybook. I just did it and its working now
