### ISSUE TITLE
Version 2.0.0-3 doesn't work with SSR

### ISSUE THREAD

**Issue by idrakimuhamad** [couds/react-bulma-components#66]
After updating to 2.0.0-3, I'm getting the `window are not defined` error. I'm using Next.js so this error likely happened at server side, which make sense. Apart from requiring the component on componentDidMount on every each usage, how can I do it easily? I seems to be getting this from `Button`, `Heading` and others.

**Comment by couds** [comment]
Weird, can you setup an example project where this is happening? I'm using that version with SSR (Without Next.js) and its works.

**Comment by idrakimuhamad** [comment]
You can try https://github.com/idrakimuhamad/sample-bulma-next

I only loaded the `Button` component in this case. In this repo I didn't set any custom webpack config or next config.

```
ReferenceError: window is not defined
    at Object.<anonymous> (webpack://react-bulma-components/webpack/bootstrap:8:0)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at Object.react-bulma-components (webpack:/external "react-bulma-components":1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 69136624c0b9ffca3349:21:0)
    at Object../pages/index.js (/Users/idraki/Developments/sample-bulma-next/.next/server/bundles/pages/index.js:82:81)
    at __webpack_require__ (webpack:/webpack/bootstrap 69136624c0b9ffca3349:21:0)
    at Object.3 (/Users/idraki/Developments/sample-bulma-next/.next/server/bundles/pages/index.js:107:18)
    at __webpack_require__ (webpack:/webpack/bootstrap 69136624c0b9ffca3349:21:0)
    at module.exports../pages/index.js.Object.defineProperty.value (webpack:/webpack/bootstrap 69136624c0b9ffca3349:68:0)
    at Object.<anonymous> (/Users/idraki/Developments/sample-bulma-next/.next/server/bundles/pages/index.js:73:10)
```

**Comment by couds** [comment]
Sorry I'm a little sick right now. I will try to check this during the weekend

**Comment by idrakimuhamad** [comment]
No problem man. Get well soon.

**Comment by couds** [comment]
@idrakimuhamad this issue didn't happen to you with the 1.4.5? I did some research and what changed was the webpack version. I will continue doing some test and try to fix this before the official release of the version 2.

Also if possible I recommend to you to use use the components directly `import Columns from 'react-bulma-components/lib/components/columns'` this will reduce the bundle size but will require some configuration on you webpack.

**Comment by idrakimuhamad** [comment]
I'm using 1.5.0 right now and not having any problem like this.

**Comment by couds** [comment]
Can you try the version 2.0.0-6 (should be fixed now)

**Comment by idrakimuhamad** [comment]
Yay! Its working. Thanks man.
